### ISSUE TITLE
Impossible to see the BOM effectivity

### ISSUE THREAD

**Issue by hadrienguiducci** [ArasLabs/effectivity-sample-application#1]
Hi,

I install the  Effectivity sample and when I go to Part and select BOM Effectivity I get the following message : "Tree Grid Definition Error. Content is not available. Please, contact admin for more details."

Any idea ? 

Thanks,
Hadrien
![image](https://user-images.githubusercontent.com/32719408/44712911-38e17380-aab2-11e8-903f-3b106f162c4b.png)

**Comment by EliJDonahue** [comment]
Hi Hadrien,

To view the BOM Effectivity tab, you first need to resolve the Part BOM structure by effectivity. [The Effectivity Services Sample Application documentation](https://github.com/ArasLabs/effectivity-sample-application/blob/master/Documentation/Effectivity%20Services%20Sample%20Application.pdf) includes steps for resolving the structure in Section 5.5. If you still see the message after resolving the structure, let us know.

Eli

**Comment by hadrienguiducci** [comment]
Hi Eli,

I was doing that but I was not entering the date criteria.

Hadrien
